# Generated by Django 2.0.2 on 2018-05-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_common_words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topwords',
            name='user_project',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
