# Generated by Django 2.0.2 on 2018-05-27 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('most_common_words', '0003_auto_20180527_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topwords',
            name='user_project',
        ),
        migrations.AddField(
            model_name='topwords',
            name='name_project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='upload_file.Document'),
        ),
        migrations.AddField(
            model_name='topwords',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
