# Generated by Django 2.0.2 on 2018-12-26 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('most_common_words', '0005_auto_20180528_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_of_words', models.SmallIntegerField(default=0)),
                ('amount_of_unique_words', models.SmallIntegerField(default=0)),
                ('amount_of_unknown_words', models.SmallIntegerField(default=0)),
                ('name_project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='upload_file.Document')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
