# Generated by Django 2.0.2 on 2018-12-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('most_common_words', '0006_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='user',
        ),
    ]
