# Generated by Django 2.0.2 on 2018-12-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_common_words', '0007_remove_statistics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='amount_of_unique_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='amount_of_unknown_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_amount_of_words',
            field=models.IntegerField(default=0),
        ),
    ]
